const RecipeActionTypes = {
    GET_MOST_RECENT_RECIPES_START: 'GET_MOST_RECENT_RECIPES_START',
    GET_MOST_RECENT_RECIPES_SUCCESS: 'GET_MOST_RECENT_RECIPES_SUCCESS',
    GET_ALL_RECIPES_FAILURE: 'GET_ALL_RECIPES_FAILURE',
    GET_MOST_LIKED_RECIPES_START: 'GET_MOST_LIKED_RECIPES_START',
    GET_MOST_LIKED_RECIPES_SUCCESS: 'GET_MOST_LIKED_RECIPES_SUCCESS',
    CHANGE_CLASS_NAME: 'CHANGE_CLASS_NAME',
    KEEP_PAGE: 'KEEP_PAGE'
}

export default RecipeActionTypes