const sagaActionTypes = {
    GET_MOST_RECENT_RECIPES_START: 'GET_MOST_RECENT_RECIPES_START',
    GET_MOST_LIKED_RECIPES_START: 'GET_MOST_LIKED_RECIPES_START',
    GET_RECIPE_BY_ID_START: 'GET_RECIPE_BY_ID_START',
    GET_MY_RECIPES_START: 'GET_MY_RECIPES_START',
    LOG_USER: 'LOG_USER',
    SIGN_UP_USER_START: 'SIGN_UP_USER_START',
    GET_ME: 'GET_ME',
    LIKE_RECIPE: 'LIKE_RECIPE',
    DISLIKE_RECIPE: 'DISLIKE_RECIPE',
    KEEP_PAGE: 'KEEP_PAGE'
}

export default sagaActionTypes