const sagaActionTypes = {
    GET_MOST_RECENT_RECIPES_START: 'GET_MOST_RECENT_RECIPES_START',
    GET_MOST_LIKED_RECIPES_START: 'GET_MOST_LIKED_RECIPES_START',
    GET_RECIPE_BY_ID: 'GET_RECIPE_BY_ID',
    LOG_USER: 'LOG_USER',
    GET_USER: 'GET_USER',
    LIKE_RECIPE: 'LIKE_RECIPE',
    DISLIKE_RECIPE: 'DISLIKE_RECIPE',
    KEEP_PAGE: 'KEEP_PAGE'
}

export default sagaActionTypes