const sagaActionTypes = {
    GET_MOST_RECENT_RECIPES_START: 'GET_MOST_RECENT_RECIPES_START',
    GET_MOST_LIKED_RECIPES_START: 'GET_MOST_LIKED_RECIPES_START',
    GET_RECIPE_BY_ID: 'GET_RECIPE_BY_ID',
    KEEP_PAGE: 'KEEP_PAGE'
}

export default sagaActionTypes